### ISSUE TITLE
Docs : Homepage Slideshow keeps shifting whole page contents

### ISSUE THREAD

**Issue by AnilSeervi** [kimlimjustin/xplorer#102]
### **Describe the bug**
The Slideshow in the [Homepage](https://xplorer.vercel.app/) has images with different dimensions and the layout around it keeps shifting the content that below it as the slideshow changes the Images.

### **Expected behavior**
A smooth transition of slideshow without shifting content of page.

**Comment by kimlimjustin** [comment]
This can be fixed by resizing the image I guess, I'll deliver the fix tonight. (If you want to, just let me know :) )

**Comment by AnilSeervi** [comment]
> 
> 
> This can be fixed by resizing the image I guess, I'll deliver the fix tonight. (If you want to, just let me know :) )

Go ahead.
Also the link `Xplorer the Docs` in Homepage is a `<a>` tag that causes refresh of the page.
