### ISSUE TITLE
Build workflow failing

### ISSUE THREAD

**Issue by im-coder-lg** [kimlimjustin/xplorer#120]
### Description

So, on #105 I had a failing check. On deeper inspection, I discovered that @kimlimjustin hasn't set a personal access token in the repository secrets and some more unrelated errors are showing up.

### Steps To Reproduce

Check the workflows

### Expected behaviour

It is actually supposed to be successful since all I changed was the docs code, not the Xplorer app code.

### Xplorer Version

not relevant

### Operating System Version

not relevant, although it happens on all build OSes

### Additional Information

The zip file contains logs that I downloaded from GitHub.

[logs_1413.zip](https://github.com/kimlimjustin/xplorer/files/7270788/logs_1413.zip)

**Comment by kimlimjustin** [comment]
Fixed via 469633c3cb51be8339127fd45bca8e7593a81cad

**Comment by im-coder-lg** [comment]
Thought the same... Anyway, thanks!
