### ISSUE TITLE
HomePage Slideshow doesn't display images for languages except English

### ISSUE THREAD

**Issue by AnilSeervi** [kimlimjustin/xplorer#122]
### Description

- The Slideshows images on the [Homepage](https://xplorer.vercel.app/) doesn't display images for homepages of other languages.

### Expected behavior

- Display images on slideshow

### Xplorer Version

v0.1.0

### Operating System Version

Windows, android

**Comment by im-coder-lg** [comment]
@AnilSeervi Are you trying to mean that once you try changing the language, the homepage has some bugs?

**Comment by im-coder-lg** [comment]
Oh, understood, checking it.

**Comment by im-coder-lg** [comment]
@kimlimjustin this _is_ a bug, I checked the homepage. On the English language, it shows the slideshow but not on Indonesian & other.

**Comment by kimlimjustin** [comment]
Just realized it, I'll fix it as soon as I could use my computer

**Comment by AnilSeervi** [comment]
Can I work on this?

**Comment by im-coder-lg** [comment]
Well, if you can. I am not a kinda big expert on this, so you can do it, I can maybe help with grammatical errors and markdown.

**Comment by kimlimjustin** [comment]
> Can I work on this?

Oh yeah sure, I forgot about this issue lmao (due to another issues on Xplorer itself)
