### ISSUE TITLE
download folder is not opening

### ISSUE THREAD

**Issue by HEGADE** [kimlimjustin/xplorer#123]
### Description

when I opened downloads folder it shows blank transparent screen   (windows os)

### Expected behavior

should open downloads folder

### Xplorer Version

0.1.0

### Operating System Version

windows

**Comment by im-coder-lg** [comment]
Can you share a video recording for the same?

**Comment by HEGADE** [comment]
> Can you share a video recording for the same?

https://user-images.githubusercontent.com/60566946/135704728-5258994f-871f-4e12-a463-109dc2900f51.mp4

**Comment by im-coder-lg** [comment]
Can you try building the app from the source? Note: this needs Node JS, Git and `Desktop Development for C++` package which is around 5 GB(C++ package). Since some components are based on C++, you need the C++ package.

**Comment by im-coder-lg** [comment]
PS: Install it on the `C:` drive since I noticed it has more storage.

**Comment by HEGADE** [comment]
> PS: Install it on the `C:` drive since I noticed it has more storage.

I have installed it  on the c drive it self

**Comment by HEGADE** [comment]
> Can you try building the app from the source? Note: this needs Node JS, Git and `Desktop Development for C++` package which is around 5 GB(C++ package). Since some components are based on C++, you need the C++ package.

okI will try that

**Comment by im-coder-lg** [comment]
I was trying to tell you to get the C++ package inside the C drive

**Comment by HEGADE** [comment]
> I was trying to tell you to get the C++ package inside the C drive
oh ,ok

**Comment by HEGADE** [comment]
sorr

> I was trying to tell you to get the C++ package inside the C drive

y to ask this question here ,but where else from github i can connect with you

**Comment by kimlimjustin** [comment]
This has been addressed as common problems, please read this https://xplorer.vercel.app/docs/common_problems/

**Comment by kimlimjustin** [comment]
@HEGADE please try it before building from source, if its not working please tell me

**Comment by HEGADE** [comment]
> @HEGADE please try it before building from source, if its not working please tell me

nope I tried ,now it's not showing blank transparent screen ,but instead it's showing loading slider

**Comment by im-coder-lg** [comment]
Best try now: Build from source.

**Comment by HEGADE** [comment]
> Best try now: Build from source.

i have done that

**Comment by HEGADE** [comment]
https://user-images.githubusercontent.com/60566946/135705444-2b87f52c-fd7e-4e28-9d59-72c259cef5a1.mp4

**Comment by im-coder-lg** [comment]
Wait wdym?

**Comment by im-coder-lg** [comment]
New bug? Have you turned off `Extract exe from icon`?

**Comment by HEGADE** [comment]
> New bug? Have you turned off `Extract exe from icon`?

nope

**Comment by im-coder-lg** [comment]
Then do it and try again.

**Comment by HEGADE** [comment]
> Then do it and try again.

ok I will do that and inform u later

**Comment by kimlimjustin** [comment]
> New bug? Have you turned off `Extract exe from icon`?

This is what I meant, this should fix it, also I think that I'll probably disable this as default in future release

**Comment by HEGADE** [comment]
> > New bug? Have you turned off `Extract exe from icon`?
> 
> This is what I meant, this should fix it, also I think that I'll probably disable this as default in future release

I guess u should highlight this in documentation

**Comment by kimlimjustin** [comment]
I added it on Common Problems section, but I'll just disable it as default

**Comment by kimlimjustin** [comment]
Also, @HEGADE does it working rn? I'm closing this if it's working

**Comment by HEGADE** [comment]
> Also, @HEGADE does it working rn? I'm closing this if it's working

yes now it is working

**Comment by kimlimjustin** [comment]
Glad to here it!

**Comment by HEGADE** [comment]
> Glad to hear it!

I will use this as my primary file explorer ,and will inform you anything goes wrong

**Comment by kimlimjustin** [comment]
> > Glad to hear it!
> 
> I will use this as my primary file explorer ,and will inform you anything goes wrong

Thanks!
