### ISSUE TITLE
markdown Link not rendered in docs

### ISSUE THREAD

**Issue by AnilSeervi** [kimlimjustin/xplorer#125]
### Description

here link in https://xplorer.vercel.app/docs/common_problems#xplorer-is-unstable-after-installing-it hasn't rendered a `<a>` tag

### Expected behavior

a link

### Xplorer Version

v0.1.0

### Operating System Version

Windows, android

**Comment by kimlimjustin** [comment]
Which a tag do you mean?

**Comment by AnilSeervi** [comment]
`a` tag within the `xplorer is unstable after installing` detail tag.

**Comment by kimlimjustin** [comment]
Ah I see, I'll fix it together with the merging of branch `theme_customization`, thanks! Also, please focus on the bug or contribute to Xplorer itself.

**Comment by AnilSeervi** [comment]
> Ah I see, I'll fix it together with the merging of branch `theme_customization`, thanks! Also, please focus on the bug or contribute to Xplorer itself.

sure thing @kimlimjustin

**Comment by kimlimjustin** [comment]
Fixed together via #127
