### ISSUE TITLE
getting stuck with single page and unable to open heavy folders

### ISSUE THREAD

**Issue by HEGADE** [kimlimjustin/xplorer#137]
### Description

when I opened  any directory and try to go back form there,  most of the time it stuck out there ,I do not it's may be happening cuz your using electron or you have not optimized the app. And if I tried to open my c  drive ,it's getting hang

### Expected behavior

should open folders properly

### Xplorer Version

0.1.0

### Operating System Version

windows

**Comment by kimlimjustin** [comment]
May I know which architecture do you use? (Motherboard and number of ram). Also please try [this](https://xplorer.vercel.app/docs/common_problems/)

**Comment by HEGADE** [comment]
> May I know which architecture do you use? (Motherboard and number of ram). Also please try [this](https://xplorer.vercel.app/docs/common_problems/)

64bit ,16gigs of ram,with rayzen 5

**Comment by kimlimjustin** [comment]
> > May I know which architecture do you use? (Motherboard and number of ram). Also please try [this](https://xplorer.vercel.app/docs/common_problems/)
> 
> 64bit ,16gigs of ram,with rayzen 5

This should be ok, have you tried  [this](https://xplorer.vercel.app/docs/common_problems/) ?

**Comment by HEGADE** [comment]
Yah ,i will try that

**Comment by HEGADE** [comment]
And will expect u to fix that as soon as possible

**Comment by kimlimjustin** [comment]
> And will expect u to fix that as soon as possible

I'm sorry but does it work? Since I can't really fix something I don't really know what the problem is.

**Comment by Turbinya** [comment]
Hello @HEGADE! Сan you open the console (`ctrl+shift+i`) before going to the folder in which you are stuck and take a screenshot after you go to it? Also write the approximate number of files in this folder please

**Comment by kimlimjustin** [comment]
> Hello @HEGADE! Сan you open the console (`ctrl+shift+i`) before going to the folder in which you are stuck and take a screenshot after you go to it? Also write the approximate number of files in this folder please

Hello @stanleyowen sorry for bothering you but could you please add this into the issue template? To avoid spamming of issues.

**Comment by stanleyowen** [comment]
Sure 👍

**Comment by HEGADE** [comment]
> > And will expect u to fix that as soon as possible
> 
> I'm sorry but does it work? Since I can't really fix something I don't really know what the problem i

**Comment by HEGADE** [comment]
> > And will expect u to fix that as soon as possible
> 
> I'm sorry but does it work? Since I can't really fix something I don't really know what the problem is

**Comment by HEGADE** [comment]
> > And will expect u to fix that as soon as possible
> 
> I'm sorry but does it work? Since I can't really fix something I don't really know what the problem is8 had

**Comment by HEGADE** [comment]
> > And will expect u to fix that as soon as possible
> 
> I'm sorry but does it work? Since I can't really fix something I don't really know what the problem is.
No bro still the same thing

**Comment by HEGADE** [comment]
> > And will expect u to fix that as soon as possible
> 
> I'm sorry but does it work? Since I can't really fix something I don't really know what the problem is.

No bro still the same thing

**Comment by kimlimjustin** [comment]
> Hello @HEGADE! Сan you open the console (ctrl+shift+i) before going to the folder in which you are stuck and take a screenshot after you go to it? Also write the approximate number of files in this folder please

Please do this

**Comment by stanleyowen** [comment]
Hi @HEGADE, if this problem still not working for you, please open the `Console` section in the `xplorer` app using `ctrl+shift+i` shortcut and copy the error messages (if any) since it's almost impossible for us to fix this issue due to the lack of information. Thanks!
