### ISSUE TITLE
Not able to access the Hard drive 

### ISSUE THREAD

**Issue by sharikhh** [kimlimjustin/xplorer#139]
### Description

it detecting the hard drive but i am not able to access it 

### Expected behavior

i expect that it would open the drive but it didn't 

### Xplorer Version

v0.1.0

### Operating System Version

windows 10 

### Additional Information

![image](https://user-images.githubusercontent.com/73626462/135743261-e26d94ec-30ca-4457-a848-d2af4e4f744f.png)

**Comment by kimlimjustin** [comment]
Have you tried [the common problems](https://xplorer.vercel.app/docs/common_problems/) ?

**Comment by sharikhh** [comment]
![image](https://user-images.githubusercontent.com/73626462/135743737-40c226c2-bcae-42ee-904b-7bb185099356.png)
did that then 
![image](https://user-images.githubusercontent.com/73626462/135743744-f58b6702-a17a-48ad-a458-bcc65046ea60.png)
opened it from here 
![image](https://user-images.githubusercontent.com/73626462/135743755-46642dbc-acdf-4300-a4cb-75d6a5115f8b.png)
but still the same problem sir !!

**Comment by sharikhh** [comment]
anything which i am doing wrong ??

**Comment by sharikhh** [comment]
![image](https://user-images.githubusercontent.com/73626462/135743811-e13111f3-8046-4fb4-8098-a462b7a4a03e.png)
it is able to access the c drive not the d drive

**Comment by kimlimjustin** [comment]
Try open the Settings, and disable `Extract exe file icon and make it as preview` option

**Comment by sharikhh** [comment]
thanks a lot man 
the design is epic keep making and bulding like this

**Comment by kimlimjustin** [comment]
Thanks!
