### ISSUE TITLE
Hi,I like your application very much. But it didn't work well.

### ISSUE THREAD

**Issue by ololee** [kimlimjustin/xplorer#158]
### Description

I am not a `ts` programmer, and I develop `FileExplorer` for my company. I think I still have a better say in this. Your file browser interface is beautiful, but it's terrible to use. Compared with the browser that comes with the operating system, when viewing a large number of files, the speed is very slow, crashes, or even freezes. I think you can try to use C/C++/OC and other higher-performance languages to process the file and return it to ts instead of using ts’ file API. I used java to develop a file browser for Android, and I found that java The File class is too perfect, so that the speed is very poor, so I use C to process the file and return it to java. The speed is improved by about 6 times, but I don't know if it is suitable for ts. Looking forward to your better products.

### Steps To Reproduce

Insert the USB flash drive
Open a catalog of 3000 pictures
Application Not Responsed.....

### Expected behavior

Very smooth display of files, it’s best to use pagination to load

### Xplorer Version

first version

### Operating System Version

Windows 10&&ubuntu 20&&mac mini m1( Big Sur)

### Additional Information

just a user.

**Comment by im-coder-lg** [comment]
> I think you can try to use C/C++

Xplorer does use C++ for some Windows modules. Maybe you can try building the app since so many commits occurred since 0.1.0
