### ISSUE TITLE
Migrating to Tauri and rebranding of Xplorer ❗

### ISSUE THREAD

**Issue by kimlimjustin** [kimlimjustin/xplorer#171]
After releasing the first version of Xplorer and publishing an article on [Forem](https://dev.to/kimlimjustin/i-wrote-a-fully-functioning-file-explorer-using-typescript-1e4n), the article and this repository went into trending 🚀. Thanks a lot for it.

During that period, I received many inputs regarding the performance of Xplorer, I actually realized this when developing Xplorer but I thought that developing in Electron with JS stacks will bring more productivity to the user as it's _lingua franca_ on Software Development and is easier to maintain, and so I choose to ignore it until someone commented in my post to let me try [Tauri](https://tauri.studio) as an alternative to Electron.

I tried it and boom 💥! The performance went rocket  (although maybe it's not as fast as the native one, I'll continually try to improve) as it now relies on Rust as the backend to handle (fetch) files and return it to typescript to display it, the size and memory consumption also drop a lot after trying to migrate it. Please note that the migrating process is **under progress** via the [`rebrand`](https://github.com/kimlimjustin/xplorer/tree/rebrand) branch. Detailed comparison will be posted on the next release which will be after the completion of migrating. (Estimate middle of November).

The rebrand of Xplorer will be polyglot as it uses Rust as backend, HTML, SCSS, and Typescript as the frontend look. The detailed change will be delivered together with the rebranding.

In addition, Xplorer will be refactored to be easily customizable and you can use Xplorer for your product on the cloud 🚀 by doing some configurations. Detailed documentation and a video tutorial will be posted after the completion of the code migration.

Please note that some features like dragging files from Xplorer into another app will be gone as Tauri does not support it right now, for those who need this feature can stay on the 0.1.0 version.

The last but not the least, Xplorer icon has changed. This is the new icon:
![icon](https://user-images.githubusercontent.com/61906684/139273868-139bac4f-fbaa-4df0-bbb9-af752ceddfbf.png)

Stay tuned for the next release!

**Comment by kimlimjustin** [comment]
Migrated via #173

**Comment by michael-dm** [comment]
Hello @kimlimjustin, did you came up with a workaround for supporting drag & drop since then ?

**Comment by xgdgsc** [comment]
I feel the migration might be too early considering the long list of unresolved electron feature parity of tauri. People want cross platform apps but with a native look. The current weird non native theme on all platforms and with limited basic file manager functions implemented is a really bad first impression. I don' t think your performance issue has anything to do with using electron. It doesn' t perform well in current status also.
