### ISSUE TITLE
Contributing Guidelines Don't Exist

### ISSUE THREAD

**Issue by WubzyGD** [kimlimjustin/xplorer#181]
Not sure if this is the wrong place to mention this or if you're already aware, but I was looking to contribute to Xplorer and the guidelines page doesn't exist :(

**Comment by kimlimjustin** [comment]
Here's the latest contribute guidelines link: https://xplorer.vercel.app/docs/Community/Contributing/

Thanks for opening this issue to remind me that the link in the CONTRIBUTING_GUIDELINES.md is not up to date. Will fix it soon.

Also, we also have [discord server](https://discord.gg/cr7mh8SV), you can ask there if you got any other doubt.

Thanks
