### ISSUE TITLE
Explorer closes on deleting files

### ISSUE THREAD

**Issue by VaithiSniper** [kimlimjustin/xplorer#183]
### Description

Explorer closes on deleting files in trash and process ends without deleting anything.

### Steps To Reproduce

1. Open Explorer and go to trash
2. Ctrl + A to select all files and Shift + Del. Click on yes. 
3. Explorer closes without deleting anything. Open again to confirm.

### Expected behavior

The files are deleted and explorer doesn't crash

### Xplorer Version

v0.2.0

### Operating System Version

Windows 10 Home 20H2

### Additional Information

https://user-images.githubusercontent.com/58522375/143593942-05553646-cf29-4acb-b614-4d459e5184a5.mp4

**Comment by kimlimjustin** [comment]
Can confirm this issue, will fix it soon (or maybe tomorrow)!

Meanwhile, you can permanently delete items from trash by right click on the Trash page, then clicking `Permanently delete all files`, it works (hopefully).

Btw, Xplorer is named as "Xplorer", not "Explorer" xd.

Thanks anyways for reporting this issue
