### ISSUE TITLE
Resizing window breaks view

### ISSUE THREAD

**Issue by angkira** [kimlimjustin/xplorer#185]
### Description

Using Xplorer in half of screen I`m face to breaking a view - window tools, tabs

It is a minor bug just to remember abount responsive view :)

![image](https://user-images.githubusercontent.com/14203639/143682339-3a2108dd-075e-42f3-bbc4-d388e4cc40a4.png)

### Steps To Reproduce

1. Open Xplorer
2. Make the window be small
3. Open new tab

### Expected behavior

Width of the tabs would reduce, maybe would be ellipsis

### Xplorer Version

0.2.0

### Operating System Version

Arch Linux

### Additional Information

Nice file explorer, respect for using Tauri. not the Electron. Waiting for updates, continue using

**Comment by kimlimjustin** [comment]
![image](https://user-images.githubusercontent.com/61906684/143683832-c10cf0a3-8f0e-4442-ae98-137cfd3384d6.png)

Can't really reproduce the bug either on windows or Linux (the Linux VM I tried in is Garuda Linux, Arch Linux based distro), or do you even make it smaller? 

Also, may I know if your OS is Arch Linux-based distro or clean installed Arch Linux?

**Comment by angkira** [comment]
Hi! I work on Manjaro + Gnome Shell, Wayland, maybe it is important. A few tabs also increase height of row. Maybe it is better to set it to  be constant. -- С уважением, Юрий Медведев   27.11.2021, 16:47, "Justin Maximillian Kimlim" ***@***.***>: Can't really reproduce the bug either on windows or Linux (the Linux VM I tried in is Garuda Linux, Arch Linux based distro), or do you even make it smaller?Also, may I know if your OS is Arch Linux-based distro or clean installed Arch Linux?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kimlimjustin** [comment]
> A few tabs also increase height of row. Maybe it is better to set it to  be constant. 

It's actually constant here tho, maybe I'll try to make the sidebar collapsable when it's resized to small, but can't be done really soon tho

**Comment by Lilkedus** [comment]
## Issue 1
I've faced the same issue on macOS Monetary.

It occurred when I resized Xplorer around the 556px breakpoint
<img width="580" alt="resized image of the xplorer window" src="https://user-images.githubusercontent.com/71512866/147780660-c48296e5-708a-45f6-a586-5345a62e4e8c.png">

Although I didn't find any bugs with the control buttons (Minimize, Maximize, Restore buttons) or with the tabs, the file-path element's height did increase.

## Issue 2
The window does not resize when I open the developer inspector tools and resize it while the console is open, and then close it. Here is a video showing the problem:


https://user-images.githubusercontent.com/71512866/147783762-b6a6047a-c6a5-4ad8-aeb6-0472db458d00.mov

## Suggestion for Issue 1
Perhaps you a minimum resize breakpoint can be added. For example, if the windows hit the 600px breakpoint, you can't resize anymore. Another method could be to collapse the sidebar.
