### ISSUE TITLE
Context menu overflow hidden

### ISSUE THREAD

**Issue by uahnbu** [kimlimjustin/xplorer#186]
### Description

When the context menu is long and the web view is small, the context menu just get cut short by the limit of the web view.
![image](https://user-images.githubusercontent.com/27907396/143909507-d39d5ea2-c83b-4482-96e5-ac949c91c2f4.png)

### Steps To Reproduce

Right click on any file/folder.

### Expected behavior

Context menu extends beyond web view limit.
![image](https://user-images.githubusercontent.com/27907396/143909681-012a049e-2c4e-4d9f-99c7-f1abe4fec4d5.png)

### Xplorer Version

v0.2.0

### Operating System Version

Windows 10 21H1

**Comment by kimlimjustin** [comment]
This is indeed one of the cons of using webview which makes handling this case more complicated, this can still _theoritically_ be done by creating a new window and dynamically calculating the size but it'll be very complicated, I'll leave this for a feature request for now (I'll pick this issue when got free time)

**Comment by uahnbu** [comment]
@kimlimjustin Actually I think that the viewport cannot always hold the context menu. For example you use a small laptop screen and in the future you decide to add more items to the context menu, then the menu will definitely overflow at some time. Hence, I suggest you use a scrollbar, which will be applicable even for the current situation. You can use a left-sided one, as in [this example](https://codepen.io/uahnbu/pen/jOmMWYG) (reduce screen height to see the scrollbar).

**Comment by kimlimjustin** [comment]
make sense, will implement that when I got time to, thanks

**Comment by kimlimjustin** [comment]
made the context menu scrollable, could you please give it a try?

**Comment by uahnbu** [comment]
Actually I don't have VC build tools installed yet. Would you mind providing me with the latest built app. I'd be ready to test it out.

**Comment by uahnbu** [comment]
@kimlimjustin So finally after a day I've managed to compile the app. The scrollbar looks good. I've got a few more thing to add:
1. The scrollbar in dark mode is quite confusing as the track has light gray and the thumb has darker gray. The track should have a nearly similar color with the color of the context menu.
2. The scroll-thumb remembers its position when close, which is inconvenient. For example when I scroll to the bottom of the context menu, then right click on another folder, the newly popup context menu is still scrolled to the bottom. You should call `scrollToTop` or something alike to reset the scrollbar.

**Comment by kimlimjustin** [comment]
> The scrollbar in dark mode is quite confusing as the track has light gray and the thumb has darker gray. The track should have a nearly similar color to the context menu. Another enhancement to consider is to adjust border-radius of the thumb for easy differentiation.

I think this is a theme problem that will be covered in the customization feature

> The scroll-thumb remembers its position when close, which is inconvenient. For example when I scroll to the bottom of the context menu, then right click on another folder, the newly popup context menu is still scrolled to the bottom. You should call scrollToTop or something alike to reset the scrollbar.

Fixed!
