### ISSUE TITLE
Failed to run yarn dev

### ISSUE THREAD

**Issue by AlexHladin** [kimlimjustin/xplorer#192]
### Description

I've tried the most recent version of the Xplorer and was faced with a building issue when I run `yarn dev` command.
The issue displayed below
![image](https://user-images.githubusercontent.com/7945837/144713042-c327d5b5-5682-4bae-8681-6d848a4e52b1.png)

My Node.js version is v16.13.1
OS:  macOS Monterey 12.0.1

I guess, with the Tauri package some additional steps are required and they should be displayed in the installation section

### Steps To Reproduce

1. git clone git@github.com:kimlimjustin/xplorer.git
2. yarn install
3. yarn dev

### Expected behavior

After running `yarn dev` application should appear

### Xplorer Version

0.2.0

### Operating System Version

macOS Monterey 12.0.1

**Comment by kimlimjustin** [comment]
Under `tauri,bundle.macOS` section on the `src/tauri.conf.json` file, try removing the `license` section, it seems like the bug of Tauri.

**Comment by AlexHladin** [comment]
@kimlimjustin solution does not work for me :(

**Comment by kimlimjustin** [comment]
Could you please attach the output of `yarn run tauri info`?

**Comment by im-coder-lg** [comment]
I wonder if @AlexHladin got the Tauri dependencies on his computer.

**Comment by kimlimjustin** [comment]
> I wonder if @AlexHladin got the Tauri dependencies on his computer.

He/she got it, the error will be something saying `tauri is not recognized` if the dependencies is not installed.

**Comment by AlexHladin** [comment]
@kimlimjustin the `yarn run tauri info` returns next information

`Downloading Rust CLI...
Download Complete

Operating System - Mac OS, version 12.1.0 X64

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.2
  yarn - 1.19.1

Rust environment
  rustc - Not installed
  cargo - Not installed

App directory structure
/.husky
/out
/example
/node_modules
/docs
/scripts
/packages
/.github
/src-tauri
/lib
/api
/.git
/.vscode
/.idea
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src asset: blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../out/src
  devPath - http://localhost:8080
  bundler - Webpack

✨  Done in 10.84s.`

I guess the main issue with running `yarn dev` because I don't have installed Rust

**Comment by kimlimjustin** [comment]
Yes, please follow [this guide](https://tauri.studio/en/docs/getting-started/intro/#setting-up-your-environment) as I mentioned in [point number 3 of this section](https://github.com/kimlimjustin/xplorer#development)
