### ISSUE TITLE
NTFS Folder don't appear on windows

### ISSUE THREAD

**Issue by pharuxtan** [kimlimjustin/xplorer#202]
### Description

I have a Hard Drive that is mounted as a NTFS Folder in my SSD. But Xplorer don't show it.
<img src="https://cdn.discordapp.com/attachments/572018331444445184/923210634940792872/unknown.png"/>

That surely come from tauri fs readDir that don't detect those type of folder

### Steps To Reproduce

1. Create a new partition and mount it as a NTFS Folder
2. Go on the parent folder of this one
3. And you'll don't see it

### Expected behavior

It should show the NTFS Folder.

### Xplorer Version

v0.2.0

### Operating System Version

Windows 10 21H2

### Additional Information

PS: Folder is still accessible with the path navigator

**Comment by kimlimjustin** [comment]
Could you please try turning off `Hide system files` and `Hide hidden files` on the `Preference` page on Settings?

> That surely come from tauri fs readDir that don't detect those type of folder

Xplorer does not rely on tauri's fs, instead, Xplorer has [a custom command](https://github.com/kimlimjustin/xplorer/blob/master/src-tauri/src/files_api.rs#L235) that relies on rust's [`std::fs::readDir`](https://doc.rust-lang.org/std/fs/struct.ReadDir.html)

> PS: Folder is still accessible with the path navigator

Yes, whenever the path is correct, it will be accessible, including networks path if that's correct

**Comment by pharuxtan** [comment]
Yeah it appear when the system files are shown
<img src="https://media.discordapp.net/attachments/572018331444445184/923243222032080916/unknown.png"/>

**Comment by kimlimjustin** [comment]
Glad to hear it!

So now the thing to do is to determine if that's actually a drive, I'll work into it tomorrow, but could you detail how to reproduce (i mean any link to docs of mount partition as a drive), so that I can find that easier. Also, if it's possible, could you please try building from source and add the following code after line [140](https://github.com/kimlimjustin/xplorer/blob/master/src-tauri/src/files_api.rs#L140).

```rust
println!("{:?}", metadata);
```

and tell me which differentiates the folder? But it's okay if you can't do that, I'll try it.

thanks in advance

**Comment by pharuxtan** [comment]
Nice, to mount a partition in a folder there is the doc here: https://docs.microsoft.com/en-us/windows-server/storage/disk-management/assign-a-mount-point-folder-path-to-a-drive

And after builting with the line that you have specified, in a test folder with and without NTFS folder, it show this in shell
```
Ok(Metadata { file_type: FileType(FileType { attributes: 16, reparse_tag: 0 }), is_dir: true, is_file: false, permissions: Permissions(FilePermissions { attrs: 16 }), modified: Ok(SystemTime { intervals: 119600028000000000 }), accessed: Ok(SystemTime { intervals: 119600028000000000 }), created: Ok(SystemTime { intervals: 119600028000000000 }), .. })
Ok(Metadata { file_type: FileType(FileType { attributes: 16, reparse_tag: 0 }), is_dir: true, is_file: false, permissions: Permissions(FilePermissions { attrs: 16 }), modified: Ok(SystemTime { intervals: 132846946916799764 }), accessed: Ok(SystemTime { intervals: 132846946916799764 }), created: Ok(SystemTime { intervals: 132846946916799764 }), .. })
```

Here is the folder
<img src="https://cdn.discordapp.com/attachments/572018331444445184/923379995445964800/unknown.png"/>

**Comment by kimlimjustin** [comment]
Can't really get what differentiate them👀

how bout this?
```rust
  let symlink_metadata = fs::symlink_metadata(file_path.clone());
  let symlink_metadata = match symlink_metadata {
    Ok(result) => result,
    Err(e) => return Err(e.to_string()),
  };
  println!(
    "{:?} {:?} {:?}",
    file_path,
    symlink_metadata.file_type(),
    metadata.file_type()
  );
```

**Comment by pharuxtan** [comment]
Here we go
```
"C:/test/drive" FileType(FileType { attributes: 1040, reparse_tag: 2684354563 }) FileType(FileType { attributes: 16, reparse_tag: 0 })
"C:/test/no-drive" FileType(FileType { attributes: 16, reparse_tag: 0 }) FileType(FileType { attributes: 16, reparse_tag: 0 })
```

**Comment by pharuxtan** [comment]
I added some other files
```
"C:/test/Code" FileType(FileType { attributes: 32, reparse_tag: 0 }) FileType(FileType { attributes: 32, reparse_tag: 0 })
"C:/test/drive" FileType(FileType { attributes: 1040, reparse_tag: 2684354563 }) FileType(FileType { attributes: 16, reparse_tag: 0 })
"C:/test/no-drive" FileType(FileType { attributes: 16, reparse_tag: 0 }) FileType(FileType { attributes: 16, reparse_tag: 0 })
"C:/test/normal.txt" FileType(FileType { attributes: 32, reparse_tag: 0 }) FileType(FileType { attributes: 32, reparse_tag: 0 })
"C:/test/UkLog.dat" FileType(FileType { attributes: 1056, reparse_tag: 2684354572 }) FileType(FileType { attributes: 32, reparse_tag: 0 })
"C:/test/Windows" FileType(FileType { attributes: 1040, reparse_tag: 2684354572 }) FileType(FileType { attributes: 16, reparse_tag: 0 })
```
Code is a Hard link file
Drive is the NTFS Folder
No-drive is a normal folder
normal.txt is a normal file
UkLog.dat is a symbolic link file
Windows is a symbolic link folder

**Comment by kimlimjustin** [comment]
From what I observed is that whether it's symlink folder or mounted NTFS, its attribute is 1040, so that we can add logical conditional to check whether it's 1040, if it is, then let it be shown as a non-hidden and non-system file. Do you agree with this? I'm afraid there are some files that are being miscategorized. how do you think bout this?

**Comment by pharuxtan** [comment]
You can identify them with the reparse tag, for example the NTFS Folder as a reparse tag of 0xA0000003 (IO_REPARSE_TAG_MOUNT_POINT)
check more here: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/c8e77b37-3909-4fe6-a4ea-2b9d423b1ee4
but yeah you can make 1040 attribute file as non system, cause windows don't count them as system file

**Comment by kimlimjustin** [comment]
Unfortunately, I can't really find any resources about reparse tag implemented on Rust means that we have to implement it ourselves, which will take a lot of time, ofc. So I think I'll just make 1040 attributed files as nonsystem file/dir
