### ISSUE TITLE
Weird ghost window on mouse hover on taskbar

### ISSUE THREAD

**Issue by xgdgsc** [kimlimjustin/xplorer#231]
### Description

![image](https://user-images.githubusercontent.com/1189869/153022245-9cb2e2f3-4314-45ff-8c4a-5afdc24773f9.png)

The two window on sides are weird. I' ve only opened one win11 folder as in the middle.

Clicking on them doesn't do anything.

### Steps To Reproduce

Unknown. I just opened one window.

### Expected behavior

Only middle win11 window preview should appear

### Xplorer Version

Version: 0.3.1

### Operating System Version

OS: win32 x86_64 10.0.22000

**Comment by kimlimjustin** [comment]
Does this also occur after reopening Xplorer and/or restarting your computer?

**Comment by im-coder-lg** [comment]
Just popping up again... Can't it be Tauri? Chances are the components that might get recognized as windows...
