### ISSUE TITLE
yarn dev failed

### ISSUE THREAD

**Issue by wjw164833** [kimlimjustin/xplorer#261]
### Description

[3] Error running CLI: failed to run cargo: program not found
[3] tauri dev exited with code 1
--> Sending SIGTERM to other processes..
[0] yarn compile:watch exited with code 1
--> Sending SIGTERM to other processes..
[1] yarn sass:watch exited with code 1
--> Sending SIGTERM to other processes..
[2] yarn web exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

how to solve

### Expected behavior

按照拉取链接，运行失败

### Xplorer Version

v0.3.1

### Operating System Version

yarn install

**Comment by kimlimjustin** [comment]
Please try install [rust](https://www.rust-lang.org/tools/install).

**Comment by wjw164833** [comment]
After I installed Rust, I continued to run with errors.
![image](https://user-images.githubusercontent.com/55548747/183368163-f1bb9f6e-05d3-488c-a671-c454e72adb96.png)

**Comment by kimlimjustin** [comment]
Have you install the `cargo` command on the path?

**Comment by wjw164833** [comment]
Cargo already included in RUST installation?
It seems that restarting VSCode has been resolved.
But there seems to be a new problem
![image](https://user-images.githubusercontent.com/55548747/183371330-0f2fcc60-f808-49d6-84b8-a7ce97b585ee.png)
thanks a lot!!

**Comment by kimlimjustin** [comment]
Does this panic happen soon after you run it, or if you could, could you please send a screenrecord?

**Comment by wjw164833** [comment]
Thanks！
I ran it successfully. I guess I still need to learn more!!!!
