### ISSUE TITLE
Xplorer domain registration lapsed

### ISSUE THREAD

**Issue by calebstewart** [kimlimjustin/xplorer#291]
The domain `xplorer.space` has expired.

![Screenshot_20231223-235404.png](https://github.com/kimlimjustin/xplorer/assets/7529189/79fae5b9-6561-44fc-b8f2-8cbb84d88214)

**Comment by kimlimjustin** [comment]
Yes, I've noticed it. I'm still collecting money as I'm running out of cash to renew it.

**Comment by MikeTheGreat** [comment]
Would GitHub Pages work? It's free and good for static hosting.
(I say, with the confidence of a person who doesn't have to do the actual work :). )

Thank you for sharing the project!  It's great!

**Comment by kimlimjustin** [comment]
> Would GitHub Pages work? It's free and good for static hosting. (I say, with the confidence of a person who doesn't have to do the actual work :). )
> 
> Thank you for sharing the project! It's great!

Nope, I don't think so; Besides the static website, there are actually some dynamic components working.

**Comment by BWWIT** [comment]
Consider putting a note on the github frontpage (readme) ;-)
A lot of people will waste time and some might even create a bug-report :-P

**Comment by kimlimjustin** [comment]
Please refer to https://xplorer-kimlimjustin.vercel.app/ in the meantime; I've requested the payment to fix this issue, which will be up again in hours or so. Btw, please consider in sponsoring this projects

**Comment by kimlimjustin** [comment]
xplorer.space is now online, yey!
