### ISSUE TITLE
Closing the only One Tab Doesn't Close the Entire Application

### ISSUE THREAD

**Issue by stanleyowen** [kimlimjustin/xplorer#34]
**Describe the bug**
Closing the only one tab by clicking the `x` button won't close the entire application and it returns the following error message:
```
VM886 E:\xplorer\outs\src\Components\tab.js:26 Uncaught TypeError: Cannot read property 'BrowserWindow' of undefined
    at HTMLSpanElement.<anonymous> (VM886 E:\xplorer\outs\src\Components\tab.js:26)
```

**To Reproduce**
1. Launch xplorer
2. Click on the `x` button which is located in the inner right tab
3. See error

**Expected behavior**
Clicking the `x` button should close the entire application.

**Screenshots**
![Closing the only One Tab Doesn't Close the Entire Application](https://user-images.githubusercontent.com/69080584/131203506-d068ecd4-a7f2-4afb-b17a-2d2e3af8d945.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 21H1 19043.1165

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by kimlimjustin** [comment]
Actually, this is a problem with typescript, but anyway, I've committed a fix.
