### ISSUE TITLE
Not Working on Windows OS

### ISSUE THREAD

**Issue by stanleyowen** [kimlimjustin/xplorer#4]
**Describe the bug**
`Xplorer` is functioning well in `Linux` Operating System, however when I tried to run on `Windows` Operating System, it doesn't preview any drives (such as Drives C, D, etc.) and turns out some error messages:
```
7VM134 E:\xplorer\src\Components\drives.js:47 Uncaught (in promise) ReferenceError: USBStick is not defined
    at Drives (VM134 E:\xplorer\src\Components\drives.js:47)
68VM134 E:\xplorer\src\Components\drives.js:47 Uncaught (in promise) ReferenceError: USBStick is not defined
    at Drives (VM134 E:\xplorer\src\Components\drives.js:47)
Drives @ VM134 E:\xplorer\src\Components\drives.js:47
async function (async)
Drives @ VM134 E:\xplorer\src\Components\drives.js:9
(anonymous) @ VM133 E:\xplorer\src\Components\home.js:91
```

**To Reproduce**
1. Clone `xplorer` repository on `Windows` Operating System
2. Run `npm i` and `npm start`
3. See error

**Expected behavior**
`xplorer` should not return those error messages and users are able to view their Disks Partition details.

**Screenshots**
![image](https://user-images.githubusercontent.com/69080584/117253328-4eb5b200-ae71-11eb-828b-681624e10815.png)

Desktop (please complete the following information):
 - OS: Windows 10 OS Version 2009 (Build 19042.964)
 - Browser Chrome
 - Version 90.0.4430.93

**Comment by kimlimjustin** [comment]
Thanks, @stanleyowen! This issue has been solved by the latest commit, please try it!
