### ISSUE TITLE
Missing Icon for `mp4` Extension

### ISSUE THREAD

**Issue by stanleyowen** [kimlimjustin/xplorer#42]
**Describe the bug**
I notice that the icon for the `mp4` extension is missing, which returns the following error messages in console:
```
Uncaught SyntaxError: Invalid hexadecimal escape sequence
error (async)
(anonymous) @ VM150 C:\Users\Stanley Owen  VGC\AppData\Local\Programs\xplorer\resources\app.asar\outs\src\Components\Files\File Operation\open.js:1
async function (async)
(anonymous) @ VM150 C:\Users\Stanley Owen  VGC\AppData\Local\Programs\xplorer\resources\app.asar\outs\src\Components\Files\File Operation\open.js:1
displayFiles @ VM150 C:\Users\Stanley Owen  VGC\AppData\Local\Programs\xplorer\resources\app.asar\outs\src\Components\Files\File Operation\open.js:1
openDir @ VM150 C:\Users\Stanley Owen  VGC\AppData\Local\Programs\xplorer\resources\app.asar\outs\src\Components\Files\File Operation\open.js:6
async function (async)
openDir @ VM150 C:\Users\Stanley Owen  VGC\AppData\Local\Programs\xplorer\resources\app.asar\outs\src\Components\Files\File Operation\open.js:6
openFileHandler @ VM150 C:\Users\Stanley Owen  VGC\AppData\Local\Programs\xplorer\resources\app.asar\outs\src\Components\Files\File Operation\open.js:1
```

**To Reproduce**
1. Go to the directory which contain `mp4` file(s)
2. See error

**Expected behavior**
The mp4 extension should have an appropriate icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/69080584/133747684-2209ad70-bb0f-49bf-be39-b7e021c50dd6.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 11 21H2 22000.194
 - App Version: v0.1.0

**Additional comment**
Does this problem happen again after restarting the app? Yes

**Comment by kimlimjustin** [comment]
Could you please try with the latest commit?

**Comment by stanleyowen** [comment]
I won't able to reproduce this issue again after pulling the latest commit, thanks!
