### ISSUE TITLE
Consider Adding #hacktoberfest Label

### ISSUE THREAD

**Issue by dkhd** [kimlimjustin/xplorer#45]
Hi! 

Thank your for making this great project.

With the Hacktoberfest is already around the corner, you could consider adding Hacktoberfest label for the issues and repository topic to increase the contribution in this project.

More about Hacktoberfest: [https://hacktoberfest.digitalocean.com/](https://hacktoberfest.digitalocean.com/)

**Comment by kimlimjustin** [comment]
Woah, just know there's an event like this! I'll take a look at it soon!

**Comment by kimlimjustin** [comment]
I've added it to this repo topic, do I do it correctly? Please point out if I did it wrongly thanks

**Comment by dkhd** [comment]
Yes mas @kimlimjustin 

Now wait for the registration to open at October 1st and contributors will start to open PRs.

You might also want to find some articles about how to participate in Hacktoberfest as a Maintainer.

Salam..

**Comment by kimlimjustin** [comment]
Okay thanks! Closing this issue for now, btw, if you'd like to contribute, any PRs will be welcomed :)
