### ISSUE TITLE
Small preview of images on hover

### ISSUE THREAD

**Issue by avi12** [kimlimjustin/xplorer#49]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Similarly to how [QTTabBar](http://qttabbar.sourceforge.net/) does it:
![explorer_2021-09-26_11-45-44](https://user-images.githubusercontent.com/6422804/134800585-cdaa90ee-62ff-429a-a050-f7c72aabf95f.png)

Currently, I must double-click an image to open it
Previewing a small version on hover will be very useful

**Comment by kimlimjustin** [comment]
Great idea, will implement it! Also, you can actually preview it by selecting it and type `Ctrl + O` ([docs](https://xplorer.vercel.app/docs/guides/operation/#preview-file)) Or right-clicking and click the `Preview` button

**Comment by avi12** [comment]
I cannot reach any submenu with the mouse - as soon as I try to hover it, it disappears

**Comment by kimlimjustin** [comment]
> I cannot reach any submenu with the mouse - as soon as I try to hover it, it disappears

You should click the menu and the submenu will be there, for now, this is a known bug, will refactor it soon!
