### ISSUE TITLE
The hover transition on items should be changed

### ISSUE THREAD

**Issue by avi12** [kimlimjustin/xplorer#50]
https://user-images.githubusercontent.com/6422804/134800908-eab4d9d2-644f-4d13-a052-7b37ca1f5053.mp4

IMO, it should simply change the background color, nothing else

**Comment by kimlimjustin** [comment]
Erm, I think this is not a bug, it's just a style preference, I'll add the feature on setting to turn this feature off. (This actually looks nice on the Grid View for me haha)

**Comment by avi12** [comment]
> (This actually looks nice on the Grid View for me haha)

Exactly, it works on a grid, not on a list, where each `<div>` is too wide

**Comment by kimlimjustin** [comment]
> > (This actually looks nice on the Grid View for me haha)
> 
> Exactly, it works on a grid, not on a list, where each `<div>` is too wide

Thanks for your feedback, I'll consider disable it on default on the list view. (This feature will be implemented after I refactor some of the stylings)

**Comment by avi12** [comment]
Also, I recommend trying to use the CSS grid

**Comment by avi12** [comment]
It seems like you do not use any JavaScript framework
Is there a reason for it?

**Comment by kimlimjustin** [comment]
> Also, I recommend trying to use the CSS grid

Ye, I used it for some of the layouts. If you can improve it, PR will be welcomed :)

> It seems like you do not use any JavaScript framework
> Is there a reason for it?

The size of the app will be much larger, I tried it before and it takes more than 100+ MB for the `exe` file whereas the size now is just around 70MB (even this, I'm still trying to make it smaller). In addition, using a framework will consume more RAM (even without it, Xplorer consumes about 200 MB of RAM, I know this is OK for most people, but smaller RAM consumption will always be better, isn't it?)

However, if you got any better solution for this, any PR will always be welcomed :)

**Comment by avi12** [comment]
Did you consider using a framework like [Svelte](https://svelte.dev)?

**Comment by kimlimjustin** [comment]
> Did you consider using a framework like [Svelte](https://svelte.dev)?

Svelte looks good but I have a doubt about the memory usage, I can test it after my work on the theme plugin is done, or if you want to help, please try it and check how much memory usage does it take up? If the `exe` size is logical, I'll migrate into it.

**Comment by avi12** [comment]
The thing with Svelte is that it doesn't use a runtime
Rather, it's a compiler whose goal is to produce the best JavaScript code to achieve what you're instructing it to do

**Comment by avi12** [comment]
I'm currently busy working on [youtube-downloader](https://github.com/avi12/youtube-downloader), as soon enough I might start working for a company, leaving me with very little free time in my hands

**Comment by kimlimjustin** [comment]
Hmm okay, I'll take a look at it by myself when I got time.
