### ISSUE TITLE
Not running on M1 macOS Monterey

### ISSUE THREAD

**Issue by JhaAman** [kimlimjustin/xplorer#52]
Hey, excited to check out Xplorer!

Unfortunately, I’m not able to open the application. I’m using an M1 Macbook Air, 8gb. It’s running a beta version of macOS 12 Monterey. It says "The application “Xplorer.app” can’t be opened.” when I click on it in /Applications

**Comment by kimlimjustin** [comment]
Do you install the correct installer? (the `dmg` file). I didn't test it on M1 macOS yet, but I think it should be ok, or could you try to build from the source, by cloning this repo?

**Comment by kimlimjustin** [comment]
Could you please try [this](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac)?

**Comment by kimlimjustin** [comment]
Okay thanks

**Comment by JhaAman** [comment]
@kimlimjustin 
Building from source worked. Specifically, I used `yarn build:mac`. I copied the .app generated into /Applications, and it works. It asked for permissions to open every single top-level folder (Documents, Downloads etc) which didn’t happen when I used `yarn start` - not sure why. 

Another thing of note: in the logs when building, all of it looked successful except this one part:
`skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=  1) 0CCF68339009C395E37A57E8A69633EE9520F21B "999990396067274@prodepdg.t-mobile.com" (CSSMERR_TP_NOT_TRUSTED)
     1 identities found
                                                Valid identities only
     0 valid identities found`

**Comment by kimlimjustin** [comment]
Thanks for your confirming,

Regarding the permission, I think this is the macOS code design to protect user, this can be unlock by purchasing the certificate (also your error while building there), which I can't afford as student.

So It's fully working right now? If so, I'm closing the issue

**Comment by JhaAman** [comment]
Yes, should be all set to close the issue. Lack of certificate may be why I cannot download the released version.

**Comment by kimlimjustin** [comment]
Okay, thanks!
