### ISSUE TITLE
“Xplorer” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by karthikcodes6** [kimlimjustin/xplorer#57]
After installing the application, I'm getting this error when I try to open it.  

OS: MacOS M1

**Comment by kimlimjustin** [comment]
Please see the solution [here](https://xplorer.vercel.app/docs/install/#common-problems) on `Faced Windows Defender` section.

**Comment by karthikcodes6** [comment]
Hey @kimlimjustin  I'm using MacOS M1

**Comment by kimlimjustin** [comment]
Could you please try [this](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac)?

**Comment by karthikcodes6** [comment]
Yes working thanks
