### ISSUE TITLE
Back and forth mouse bindings for history navigation

### ISSUE THREAD

**Issue by Ponokefalos** [kimlimjustin/xplorer#58]
**Is your feature request related to a problem?**
More like an enhancement 

**Describe the solution you'd like**
Consider using back and forth mouse bindings automatically like most file explorers. 
As a developer I constantly make use of keyboard and mouse shortcuts. I suggest to make use of mouse bindings so user can go to previous visited path by pressing the shortcut. Same behavior applies on browsers where you can navigate to previous visited page or next page (if exists).

**Additional comment**
After some research I learned that keyboard shortcut for back and forth is ALT+left arrow and ALT+right arrow accordingly.

**Comment by kimlimjustin** [comment]
Do you mean mouse bindings by add `Back` and `Forward` on right clicking context menu? For the keyboard shortcut, `Alt + Left Arrow` and `Alt + Right Arrow` should works, is it?

**Comment by Ponokefalos** [comment]
At first I would like to thank you for you immediate response. I mean plain mouse key bindings, not the right click context menu. For example I own a Logitech mouse which has some buttons on it, the default  behavior of that buttons is to navigate you to `Back` and `Forward` on file explorers, browsers etc

**Comment by kimlimjustin** [comment]
> At first I would like to thank you for you immediate response. I mean plain mouse key bindings, not the right click context menu. For example I own a Logitech mouse which has some buttons on it, the default behavior of that buttons is to navigate you to `Back` and `Forward` on file explorers, browsers etc

Oh I see. I never think about it before. I'll do some research about it.

**Comment by Turbinya** [comment]
I can do it

**Comment by kimlimjustin** [comment]
> I can do it. I have a suitable mouse =)

Wow, thanks! PR will be welcomed! Tbh, I don't know how to do it cuz I don't have that kind of mouse.
