### ISSUE TITLE
Unable to detect phone plugged in

### ISSUE THREAD

**Issue by kimlimjustin** [kimlimjustin/xplorer#6]
Currently, technology to detect USB Drives plugged in is by:
1. Windows
   ```
   wmic logicaldisk get Caption,FreeSpace,Size,VolumeName,Description  /format:list
   ```
2. Linux and Mac
   ```
   df -P | awk 'NR > 1'
   ```

However, those commands are unable to detect the phone when plugged in, and we need to find a new way to detect drives, using any programing language that can be plugged into node.js. Any comments will be appreciated :)

**Comment by rohanvh7** [comment]
Usb detection in browsers is considered security issue.What are your thoughts?

**Comment by kimlimjustin** [comment]
> Usb detection in browsers is considered security issue.What are your thoughts?

Don't forget that you can also run native code on it. You can import c++ code using [node_api](https://nodejs.org/api/n-api.html). Indeed, there is already a feature on Xplorer implemented using c++, you can take a look at the code [here](https://github.com/kimlimjustin/xplorer/tree/master/src/Lib/node-disk-info).

In addition, Electron is not all about browser applications on the desktop. If it does, there will be no Xplorer at all, since you won't able to read files on the browser. Please differentiate between the node process and the browser process.

**Comment by rohanvh7** [comment]
Yes my bad! Thanks kim

**Comment by ctwhome** [comment]
> > Usb detection in browsers is considered security issue.What are your thoughts?
> 
> Don't forget that you can also run native code on it. You can import c++ code using [node_api](https://nodejs.org/api/n-api.html). Indeed, there is already a feature on Xplorer implemented using c++, you can take a look at the code [here](https://github.com/kimlimjustin/xplorer/tree/master/src/Lib/node-disk-info).
> 
> In addition, Electron is not all about browser applications on the desktop. If it does, there will be no Xplorer at all, since you won't able to read files on the browser. Please differentiate between the node process and the browser process.

Hi, I am intrigued by the project. You mention that the browser can't read the files, but do you think the new [File System Access API](https://web.dev/file-system-access/) can change that? And maybe removing eventually the need to use any backend task to read/write files?

**Comment by kimlimjustin** [comment]
> Hi, I am intrigued by the project. You mention that the browser can't read the files, but do you think the new File System Access API can change that? And maybe removing eventually the need to use any backend task to read/write files?

The simple answer is No. Besides writing and reading files, Xplorer also takes care of reading drives, disks, networks (in the future), and many others which File System Access API does not allow to afaik, besides, it's bad for UX when you download and app and it still asking you for those permissions.

**Comment by kimlimjustin** [comment]
Just an update, the technology to reading USB has changed as #173 get merged, but the issue still remains, I'll open another issue later.
