### ISSUE TITLE
Make close settings action to match the whole settings button

### ISSUE THREAD

**Issue by Ponokefalos** [kimlimjustin/xplorer#61]
**Is your feature request related to a problem?**
More like an enhancement 

**Describe the solution you'd like**
When I want to close the settings view then the action (with censor: pointer) exists only in the `up arrow icon` on the top left corner instead of the whole settings button. I suggest to expand the action area to the whole settings button.

**Comment by kimlimjustin** [comment]
Closing this issue as implemented on #63
