### ISSUE TITLE
Settings Window cannot be closed.

### ISSUE THREAD

**Issue by ozgursarikamis** [kimlimjustin/xplorer#64]
**Describe the bug**

**To Reproduce**
1. Go to "Settings"
2. There is no way to close Settings window.

**Expected behavior**

Settings arrow should be downside and when I click it, nothing happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/26919233/134823312-021d306d-d5c7-47e0-8200-bf60baf54a4a.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 21H1 19043.1023]
 - App Version: [e.g. v1.0]

**Comment by kimlimjustin** [comment]
Actually, there's a way to close it, by clicking right the pointer, it will close it (https://xplorer.vercel.app/docs/guides/setting/). In addition, there is already a PR (#63) that will support closing the setting by clicking the button, not only the pointer.

Closing this for now.... Thanks.

**Comment by ozgursarikamis** [comment]
btw, I really liked the app idea. Good job.
