### ISSUE TITLE
ContextMenu code style

### ISSUE THREAD

**Issue by westtrade** [kimlimjustin/xplorer#65]
https://github.com/kimlimjustin/xplorer/blob/497e6b2b065bf44b661db2b0a97348a42fa06ae7/src/Components/Context%20Menu/contextMenu.ts#L150

I think it was better if you placed this const outside of this function in the module - and it was better if this const was wrapped by Object.freeze - because the doesn't change anywhere

**Comment by kimlimjustin** [comment]
Ah okay, thanks for your suggestion. However, don't create a PR first because I'll surely refactor the whole contextmenu (the contextmenu will supports the native contextmenu and plugin support).

**Comment by kimlimjustin** [comment]
Closing this as implemented via #154
