### ISSUE TITLE
More shortcut keys support

### ISSUE THREAD

**Issue by ledmirage** [kimlimjustin/xplorer#68]
these are some of the common shortcut keys i personally use frequently
base on my exp using file explorer in windows and linux

support the following shortcut keys:

- search (eg Ctrl+F)
- new windows (eg Ctrl+N)
- new tab (eg Ctrl+T)
- navigate Up from current folder (eg Alt+Up)
- navigate back/forward folder history (eg Alt+Left/Right)
- toggle display of hidden files (eg Ctrl+H)

Most importantly it should support configurable shortcut so user can customize them base on preference.

feel free to add more to the list

**Comment by kimlimjustin** [comment]
Noted, thanks!

Btw, some of it already exists, like navigate back/forward, new tab and toggle hidden files.

For the customization, I'm working on the `theme_customization` theme rn.

**Comment by kimlimjustin** [comment]
All of the keyboard you proposed are implemented now in the master branch, stay tuned for next release!
