### ISSUE TITLE
Drives on macOS are not valid

### ISSUE THREAD

**Issue by Lilkedus** [kimlimjustin/xplorer#7]
Xplorer on macOS is not detecting the right pen drives.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/71512866/117492925-f4087d00-af7a-11eb-86ec-83fa59490d03.png)

**Comment by kimlimjustin** [comment]
Could you please try to run these commands when USB drives plugged in?
```
system_profiler SPUSBDataType
```

```
ioreg -p IOUSB
```
