### ISSUE TITLE
Red swiggly line appears below file path input

### ISSUE THREAD

**Issue by rushabh-wadkar** [kimlimjustin/xplorer#70]
**Describe the bug**
More of an enhancement actually. A red swiggly line appears below text "**xplorer**://Home" in filepath input. That''s the spell check which spins up. I think disabling it would be nice.

**To Reproduce**
1. Click on file path input `xplorer://Home`
2. A red line appears below "xplorer" text

**Expected behavior**
should not do spellcheck on filepath input

**Screenshots**
![spellcheck-issue](https://user-images.githubusercontent.com/6323685/134847823-4b7750a2-d8f2-4a10-8f2c-36d3f9d0861a.png)

**Desktop (please complete the following information):**
 - OS Version: Ubuntu 20.04 LTS
 - App Version: v0.2.0

**Comment by rushabh-wadkar** [comment]
@kimlimjustin I have a PR ready for this change. Can I raise it ?

**Comment by kimlimjustin** [comment]
> @kimlimjustin I have a PR ready for this change. Can I raise it ?

Sure!

**Comment by kimlimjustin** [comment]
Oh yeah, there's actually a problem in which the shortcut is messed up with the input shortcut. Ex: when I focus on the input path and press `Ctrl + A`, it will select every file in which it's supposed to only select all characters on Input. Do you want to raise a PR for this?

The Abstract will be something like this:
On user press the key, before checking the shortcut if statements, check if the user is focusing the input path.

It's completely okay if you can't open this PR, I can send a fix later (but not too soon, got no time haha)

**Comment by rushabh-wadkar** [comment]
@kimlimjustin yeah sure, I can pick this up.

**Comment by kimlimjustin** [comment]
> @kimlimjustin yeah sure, I can pick this up.

Okay, TYSM!

**Comment by kimlimjustin** [comment]
Closing this issue as it's fixed.
