### ISSUE TITLE
Properties Style

### ISSUE THREAD

**Issue by im-tridevsharma** [kimlimjustin/xplorer#72]
![image](https://user-images.githubusercontent.com/62466333/134852043-722367c1-612b-4583-854e-c04ab4a30c62.png)

**Comment by rushabh-wadkar** [comment]
yes, reproducible when the file path character length is 58 characters or more.
@kimlimjustin I can take this up if you want :)

**Comment by kimlimjustin** [comment]
> yes, reproducible when the file path character length is 58 characters or more.
> @kimlimjustin I can take this up if you want :)

Tbh, I was planning to refactor the file properties, the design right now is quite ugly, isn't it? I was planning to make it as a popup modal in the center tho. However, if you want to fix that problem and also could make it prettier, yeah just go with it 👍

**Comment by rushabh-wadkar** [comment]
I won't say it's ugly but yes, it needs some redesign. I was thinking of just fixing this bug, and then we can decide on the redesigning of some components in another enhancement ticket. How about that ?

**Comment by kimlimjustin** [comment]
> I won't say it's ugly but yes, it needs some redesign. I was thinking of just fixing this bug, and then we can decide on the redesigning of some components in another enhancement ticket. How about that ?

Sure!

**Comment by kimlimjustin** [comment]
fixed via #74

**Comment by im-tridevsharma** [comment]
Bro, I want to work on the design part. If you don't mind.

**Comment by kimlimjustin** [comment]
> Bro, I want to work on the design part. If you don't mind.

Yeah sure! Any PR will be welcomed :)

**Comment by rushabh-wadkar** [comment]
@kimlimjustin or @im-tridevsharma  any update on why was this closed? Is the enhancement invalid or is it still open?

**Comment by kimlimjustin** [comment]
> @kimlimjustin or @im-tridevsharma any update on why was this closed? Is the enhancement invalid or is it still open?

I'm not sure about @im-tridevsharma , he said he wants to work on the design part, but I don't sure why he close it, maybe he will raise another issue (?)

**Comment by im-tridevsharma** [comment]
Sorry guyes it closed by mistake.

**Comment by im-tridevsharma** [comment]
There is a high color effect when hover on tab and card in Dark+ mode. I fixed it but don't have permission to push it.

**Comment by dkhd** [comment]
Hi @im-tridevsharma 

Have you successfully created the PR?

Cheers ~

**Comment by im-tridevsharma** [comment]
Due to some technical reason I had to change my OS. But now getting some new error on my system.

>>>:  error F:\git_collaboration\xplorer\node_modules\platform-folders: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: F:\git_collaboration\xplorer\node_modules\platform-folders
Output:
F:\git_collaboration\xplorer\node_modules\platform-folders>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.18.0 | win32 | x64
gyp info find Python using Python version 3.9.7 found at "C:\Users\tride\AppData\Local\Programs\Python\Python39\python.exe"
gyp http GET https://nodejs.org/download/release/v14.18.0/node-v14.18.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.18.0/node-v14.18.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.18.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v14.18.0/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v14.18.0/win-arm64/node.lib
gyp http GET https://nodejs.org/download/release/v14.18.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v14.18.0/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v14.18.0/SHASUMS256.txt
gyp http 404 https://nodejs.org/download/release/v14.18.0/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v14.18.0/win-x64/node.lib
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)    
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\git_collaboration\xplorer\node_modules\platform-folders 

Could anyone resolve this?

**Comment by kimlimjustin** [comment]
As said on the error, you have to install Visual Studio 2019 with the `Desktop development with C++` package:
![image](https://user-images.githubusercontent.com/61906684/135566194-2d65fb57-d00b-4c81-8aaf-395815591f5c.png)

**Comment by im-tridevsharma** [comment]
I installed Visual Studio 2019 with C++ Environment but now getting this error : 
>>> error F:\git_collaboration\xplorer\node_modules\platform-folders: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: F:\git_collaboration\xplorer\node_modules\platform-folders
Output:
F:\git_collaboration\xplorer\node_modules\platform-folders>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.18.0 | win32 | x64
gyp info find Python using Python version 3.9.7 found at "C:\Users\tride\AppData\Local\Programs\Python\Python39\python.exe"
gyp http GET https://nodejs.org/download/release/v14.18.0/node-v14.18.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.18.0/node-v14.18.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.18.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v14.18.0/win-arm64/node.lib
gyp http GET https://nodejs.org/download/release/v14.18.0/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v14.18.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v14.18.0/win-x86/node.lib
gyp http 404 https://nodejs.org/download/release/v14.18.0/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v14.18.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v14.18.0/SHASUMS256.txt
gyp info find VS using VS2019 (16.11.31702.278) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\tride\AppData\Local\Programs\Python\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\git_collaboration\\xplorer\\node_modules\\platform-folders\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\tride\\AppData\\Local\\node-gyp\\Cache\\14.18.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\tride\\AppData\\Local\\node-gyp\\Cache\\14.18.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\tride\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.18.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\git_collaboration\\xplorer\\node_modules\\platform-folders',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\git_collaboration\\xplorer\\node_modules\\platform-folders\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  binding.cc
  platform_folders.cpp
  win_delay_load_hook.cc
F:\git_collaboration\xplorer\node_modules\platform-folders\src\binding.cc(37,9): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [F:\git_collaboration\xplorer\node_modules\platform-folders\build\platformFolders.vcxproj]
LINK : fatal error LNK1104: cannot open file 'C:\\Users\\tride\\AppData\\Local\\node-gyp\\Cache\\14.18.0\\x64\\node.lib' [F:\git_collaboration\xplorer\node_modules\platform-folders\build\platformFolders.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\git_collaboration\xplorer\node_modules\platform-folders

**Comment by kimlimjustin** [comment]
Could you please try a restart and try [this](https://stackoverflow.com/questions/21562038/node-gyp-build-error-windows-x64) ?

**Comment by im-tridevsharma** [comment]
Yes, I did it. and now it's showing some permission issue when run command yarn dev.

>>$ yarn compile && concurrently "yarn compile:watch" "yarn sass:watch" "yarn copyfiles:watch" "yarn electron"
$ rimraf outs && tsc && yarn sass && yarn copyfiles
F:\git_collaboration\xplorer\node_modules\rimraf\bin.js:46
      throw er
      ^

[Error: EPERM: operation not permitted, unlink 'F:\git_collaboration\xplorer\outs\build\Release\module.node'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'F:\\git_collaboration\\xplorer\\outs\\build\\Release\\module.node'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kimlimjustin** [comment]
For this error, open task manager, kill `Electron`, and try again.

If it doesn't work, kill `Electron` and instead of running `yarn dev`, run `yarn compile` then `yarn start`

**Comment by im-tridevsharma** [comment]
Did same. Now these outputs come.
>>$ yarn compile && yarn sass && yarn electron
$ rimraf outs && tsc && yarn sass && yarn copyfiles
$ sass src/Public/style.scss outs/src/Public/style.css
$ node scripts/copyfiles
$ sass src/Public/style.scss outs/src/Public/style.css
$ electron ./outs/src/main.js

>>{ _: [], '$0': './outs/src/main.js' }
15:22:05.577 > Skip checkForUpdatesAndNotify because application is not packed

**Comment by kimlimjustin** [comment]
> Did same. Now these outputs come.
> 
> > > $ yarn compile && yarn sass && yarn electron
> > > $ rimraf outs && tsc && yarn sass && yarn copyfiles
> > > $ sass src/Public/style.scss outs/src/Public/style.css
> > > $ node scripts/copyfiles
> > > $ sass src/Public/style.scss outs/src/Public/style.css
> > > $ electron ./outs/src/main.js
> 
> > > { _: [], '$0': './outs/src/main.js' }
> > > 15:22:05.577 > Skip checkForUpdatesAndNotify because application is not packed

This is an expected output and a window of Xplorer will pop up. However, there're some reports of `yarn dev`/`yarn start` not working, in this case, please do the following commands:

- run `yarn compile` and wait for it to be done
- run `yarn electron`

**Comment by im-tridevsharma** [comment]
Xplorer doesn't popup so i sent this output here.

**Comment by kimlimjustin** [comment]
> Xplorer doesn't popup so i sent this output here.

Please try `yarn compile` then `yarn electron`

**Comment by im-tridevsharma** [comment]
I did same you suggested. But still window doesn't popup.

**Comment by kimlimjustin** [comment]
Could you please confirm that there's an `outs` folder with `src` folder under it? If so, could you please try to run the [Electron Boilerplate](https://www.electronjs.org/docs/tutorial/boilerplates-and-clis#electron-react-boilerplate), if it working? If not, it's problem with Electron

**Comment by im-tridevsharma** [comment]
Yes there is an outs folder with src one. I try to run electron boilerplate.

**Comment by im-tridevsharma** [comment]
Got the solution. It works with command yarn electron -m

**Comment by kimlimjustin** [comment]
Glad to here it!

**Comment by kimlimjustin** [comment]
> Hi @im-tridevsharma
> 
> Have you successfully created the PR?
> 
> Cheers ~

@im-tridevsharma successfully created a PR, however, it's about the styles (theme)'s properties (#129), I was thinking that @im-tridevsharma meant about the properties (literally the properties section)'s styling.

For the properties section's styling, do you want to work on it? @dkhd 

Thanks and Regards

**Comment by dkhd** [comment]
Ok @kimlimjustin  & @im-tridevsharma 

But just to be sure, which properties part you want me to adjust?

**Comment by kimlimjustin** [comment]
![image](https://user-images.githubusercontent.com/61906684/135717597-c102a29f-f95a-4fe1-b379-5d44fef2fe83.png)

In this section,  do you have any better idea of its styling?

**Comment by dkhd** [comment]
Sure, this part can be improved 🔥🔥🔥

**Comment by kimlimjustin** [comment]
Closing this issue as it's implemented on the master branch.
