### ISSUE TITLE
Ultra-wide support 

### ISSUE THREAD

**Issue by Dariusz1989** [kimlimjustin/xplorer#75]
Describe the bug
Ultrawide screen not supported/wide xplorer 

To Reproduce
Make it wide

Screenshots
![image](https://user-images.githubusercontent.com/13185728/134863637-f82d7b10-6ca4-4e7d-a50a-2597a50cf2a4.png)

Desktop (please complete the following information):

OS Version: Windows10x64
App Version: 0.1.0

**Comment by kimlimjustin** [comment]
This is a duplicate of #50.

**Comment by kimlimjustin** [comment]
The problem is the tilt effect on the detailed view (it only occurs on medium size monitors as well as small monitors, ultra-wide will only make it more obvious CMIIW). A fix is already in work rn.
