### ISSUE TITLE
Incorrect folder name of mappet drive

### ISSUE THREAD

**Issue by Dariusz1989** [kimlimjustin/xplorer#77]
I've mapped some network drivers & renamed them in windows explorer. It looks like the name I get in xplorer is the mapped folder not explorer-renamed name.
Would it be possible to use the new name, or let us add alias to the network drivers here? 

**To Reproduce**
Map a drive, rename it in ms explorer. Open xplorer, name is different.

**Expected behavior**
Use renamed ms explorer name.

 - OS Version: Win10x64
 - App Version: [e.g. v1.0]

**Comment by kimlimjustin** [comment]
Thanks for your feedback, will take a look into it :)

**Comment by kimlimjustin** [comment]
Does this issue still occur on v0.2.0?

**Comment by kimlimjustin** [comment]
I'll close this issue because of inactivity, please open another issue if this issue still occurs on the latest version.
