### ISSUE TITLE
How to start from code

### ISSUE THREAD

**Issue by codewithpom** [kimlimjustin/xplorer#81]
I want to know how to run it from source code without yarn.

**Comment by shuhikari** [comment]
@codewithpom  afaik, this app was built on nodejs and require its dependencies to run it from source.

If you don't want to use yarn, you probably can use `npm` from nodejs installer.

**Comment by codewithpom** [comment]
I know but command should I fire I gues ```npm start```

**Comment by shuhikari** [comment]
It would require you to install the packages first running `npm install` and after that, you must look for the scripts section of the [package.json](https://github.com/kimlimjustin/xplorer/blob/master/package.json) , if I got you right, my guess is `npm run start`.

**Comment by codewithpom** [comment]
ok Thanks

**Comment by kimlimjustin** [comment]
If you want to use npm, first run `npm install` then run `npm start` to just start the electron (no hot reload enabled), or `npm dev` to start the development process. 

DIff between `npm start` and `npm dev`:
- `npm start` doesn't support hot reload
- `npm dev` does support hot reload
