### ISSUE TITLE
can't run repo on windows (works well on mac). Also, when I build exe files on mac the don't work when I actually run them in window

### ISSUE THREAD

**Issue by LordKayBanks** [kimlimjustin/xplorer#86]
**Describe the bug**
Can't run repo on windows (works well on mac). Also, when I build exe files on Mac they don't work when I actually run them in Windows.

![image](https://user-images.githubusercontent.com/24697778/135001360-2b592aad-48b0-4b47-8740-327b809c8734.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 21H1 19043.1023]
 - App Version: [e.g. v1.0]

**Comment by LordKayBanks** [comment]
Visual Studio C++ or Visual C++?

could you please point me in the right direction on how to install Visual Studio C++ on my windows pc

**Comment by kimlimjustin** [comment]
It seems that you got into problem with npm, could you please try this? https://stackoverflow.com/a/24741740
